name: Download Artifact with Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Semantic version of the artifact to download (e.g., 1.0.0)"
        required: true
        default: "1.0.0"

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Set variables
        run: echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Fetch artifact details
        run: |
          REPO="shutter-org/artifact-giver"  # Public uploading repo
          curl -s "https://api.github.com/repos/$REPO/actions/artifacts" > artifacts.json
          cat artifacts.json | jq -r ".artifacts[] | select(.name==\"my-artifact-${VERSION}\") | .archive_download_url" > artifact-url.txt
          if [ ! -s artifact-url.txt ]; then
            echo "Error: Artifact my-artifact-${VERSION} not found." >&2
            exit 1
          fi

      - name: Download artifact
        run: |
          URL=$(cat artifact-url.txt)
          curl -sL "$URL" --output artifact.zip
          unzip artifact.zip -d artifact

      - name: List downloaded files
        run: ls -R artifact
