name: Download Artifact

on:
  push:
    branches:
      - main

jobs:
  download-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Get artifact ID
        id: get_artifact_id
        run: |
          ARTIFACT_ID=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/shutter-org/artifact-giver/actions/artifacts | jq -r '.artifacts[] | select(.name == "my-artifact-1.0.0") | .id')
          echo "Artifact ID: $ARTIFACT_ID"
          echo "artifact_id=$ARTIFACT_ID" >> $GITHUB_ENV

      - name: Download the artifact
        run: |
          gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/shutter-org/artifact-giver/actions/artifacts/${{ env.artifact_id }}/download \
          --output my-artifact-1.0.0.zip

      - name: List downloaded files
        run: ls -lh my-artifact-1.0.0.zip
